### ISSUE TITLE
Internal Server Error when opening the dashboard

### ISSUE THREAD

**Issue by caplod** [JohannesHoffmann/vapid-docker#1]
hi johannes, 
I created a new site with the following command
`docker run --rm -p 3000:3000 -v $(pwd):/usr/src/app joehoppe/vapid`

when I try to open the dashboard with http://localhost:3000/dashboard/ I get the following error:

```
GET /dashboard/sign_in 302 67 - 8.383 ms [GA1.1.117998447.1515667538]
TypeError [ERR_INVALID_ARG_TYPE]: The "key" argument must be one of type string, TypedArray, or DataView. Received type undefined
    at new Hmac (internal/crypto/hash.js:88:11)
    at Object.createHmac (crypto.js:129:10)
    at sign (/usr/local/lib/node_modules/vapid-cli/node_modules/keygrip/index.js:22:8)
    at Keygrip.sign (/usr/local/lib/node_modules/vapid-cli/node_modules/keygrip/index.js:29:38)
    at Cookies.set (/usr/local/lib/node_modules/vapid-cli/node_modules/cookies/index.js:109:30)
    at ContextSession.save (/usr/local/lib/node_modules/vapid-cli/node_modules/koa-session/lib/context.js:321:22)
    at ContextSession.commit (/usr/local/lib/node_modules/vapid-cli/node_modules/koa-session/lib/context.js:231:16)
    at session (/usr/local/lib/node_modules/vapid-cli/node_modules/koa-session/index.js:46:20)
```

**Comment by JohannesHoffmann** [comment]
Hi stefan,

thanks for your feedback! I could reproduce the error. I updated the container. Can you pls pull the latest one and try it again? If it will still not work, is it working without mounting a volume?

**Comment by caplod** [comment]
Thanks for your fix. 
It is now working as expected. ;-)
